name: klphoto
favicon: null
layout_spectrum: 0.51192
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9eb7bc'
    - '#e8e8ea'
    - '#3e302d'
    - '#e7b8a6'
    - '#ac6f39'
  brandStrength: 0.9375
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
