name: klphoto
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12282
title: Kristian Lund Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#3d3d3b'
    - '#62635e'
    - '#c4c4c6'
    - '#979ca2'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
