name: klphoto
favicon: null
layout_spectrum: 0.91676
typography_spectrum: 0.52785
title: Kristian Lund Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afaeb6'
    - '#474143'
    - '#877f8a'
    - '#291c16'
    - '#be8e77'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
